# This file is part of the research.fi service
#
# Copyright 2019 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT

version: '3.7'

services:
  angular:
    build:
      context: .
      dockerfile: openshift/Dockerfile
      target: angular
    ports:
      - '80:8080'
    restart: unless-stopped
